# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('password', models.CharField(editable=False, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=13, verbose_name='Mobile Number')),
                ('address', models.TextField(max_length=250)),
                ('package', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('mobile_no', models.CharField(blank=True, max_length=13, null=True, verbose_name='Mobile Number')),
                ('vehicle_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Vehicle Number')),
                ('from_place', models.CharField(blank=True, max_length=50, null=True)),
                ('destination_place', models.CharField(blank=True, max_length=50, null=True)),
                ('in_time', models.DateTimeField(blank=True, null=True)),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=b'uploads/member_photos')),
                ('signature', models.ImageField(blank=True, null=True, upload_to=b'uploads/signature_photos')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mapi.Member')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wb_name', models.CharField(max_length=50)),
                ('member', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='mapi.Member')),
            ],
        ),
        migrations.CreateModel(
            name='WorkBookType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True)),
                ('wb_icon', models.ImageField(blank=True, null=True, upload_to=b'uploads/workbook_icon')),
                ('mandatory_fields', models.CharField(blank=True, help_text=b'Keep it empty, will be filled while creating workbook', max_length=1250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='workbook',
            name='wb_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='mapi.WorkBookType'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='workbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapi.WorkBook'),
        ),
    ]
