# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapi', '0003_auto_20160723_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workbooktype',
            name='mandatory_fields',
        ),
    ]
