# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapi', '0007_auto_20160724_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workbooktype',
            name='mandatory_fields',
            field=models.TextField(default=b'', help_text=b"Comma separated visitor table's column name (eg: name,mobile_no)", max_length=1250),
        ),
    ]
