# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapi', '0009_auto_20160724_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='workbook',
            name='member',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='mapi.Member'),
        ),
        migrations.AlterField(
            model_name='workbooktype',
            name='mandatory_fields',
            field=models.CharField(blank=True, default=b'', max_length=1250),
        ),
    ]
