# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapi', '0010_auto_20160724_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workbooktype',
            name='mandatory_fields',
        ),
    ]
