# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapi', '0012_workbooktype_mandatory_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='workbook',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='mapi.WorkBook'),
        ),
        migrations.AlterField(
            model_name='workbooktype',
            name='mandatory_fields',
            field=models.CharField(blank=True, help_text=b'Keep it empty, will be filled while creating workbook', max_length=1250, null=True),
        ),
    ]
