# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapi', '0013_auto_20160724_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workbook',
            name='wb_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='mapi.WorkBookType'),
        ),
    ]
