# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapi', '0014_auto_20160724_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workbook',
            name='wb_icon',
        ),
        migrations.AddField(
            model_name='workbooktype',
            name='wb_icon',
            field=models.ImageField(blank=True, null=True, upload_to=b'uploads/workbook_icon'),
        ),
    ]
