# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapi', '0015_auto_20160725_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='destination_place',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='from_place',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Vehicle Number'),
        ),
    ]
