# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapi', '0016_auto_20160727_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='in_time',
            field=models.DateTimeField(),
        ),
    ]
