# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapi', '0017_auto_20160727_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='workbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapi.WorkBook'),
        ),
    ]
